name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    permissions:
      contents: read
      pull-requests: write
      
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: | 
            rustup override set nightly
            cargo build --verbose
    - name: copy user psv
      run: |
          mkdir -p C:\\Users\\runneradmin\\Documents/fantasy-tavern-maker-tui/mod_npc/
          copy -v src/npc/*.psv C:\\Users\\runneradmin\\Documents/fantasy-tavern-maker-tui/mod_npc/
    - name: Run tests
      run: cargo test --verbose
      
